# Generated by Django 4.2.11 on 2024-05-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_of_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='data',
            field=models.JSONField(default={'elements': []}),
        ),
    ]
