# Generated by Django 5.0.4 on 2024-04-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_scheme_pub_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='data',
        ),
    ]
